### PR TITLE
Fix broken hiss-kin cooldown

### PR DESCRIPTION
**Pull request by Roadhog360**
# Explanation
The type `origins:multiple` gave the hiss-kin a *separate* cooldown. You have one ability in this file that has two abilities: `rocket_jump` which is ONLY a cooldown, that doesn't apply to the next entry. The next entry, `rocket_jump` has a cooldown set to 1, which does not match the meter.

# Solution
The multiple types seem unnecessary, so I removed it. At the moment I still have the `origins:multiple` there with one type since for some reason when I remove it, it breaks the entire ability. Until I can find out what I am doing wrong in that regard, this PR remains a draft.

### CODE REVIEW

**Comment by ChrysanthCow** [comment]
This is not how it works.

Hiss-kin will damage themselves whilst using it on cooldown. Basically, you're allowed to use it off and on cooldown, it's meant as a buffer rather than a strict cooldown.

**Comment by Roadhog360** [comment]
~~So then what is the meter for? It seems pointless, what is it actually correlating to?~~

Nvm, I... *think* I get it? I'll havw to test to be sure, I don't remember the Hiss-Kin player being damaged from using it off-cooldown.

**Comment by ChrysanthCow** [comment]
> So then what is the meter for? It seems pointless, what is it actually correlating to?

Again, what I said. The meter is to tell you that you're going to take damage by using your ability.

**Comment by Roadhog360** [comment]
Damn you're right I completely misunderstood
image

**Pull request closed without merging**
